### ISSUE TITLE
Add Docker Deploy Reusable Workflow

### ISSUE THREAD

**Issue by AnthonyMonterrosa** [atomic-works/github-actions-reusable-workflows#6]
### Summary

Adds a reusable workflow that copies the docker deployment work initially created in `docker-image-alpin-linux/.github/workflows/deployment.yml` in this code snippet:
```
Publish-Docker-Image:
    needs: Create-Release
    permissions:
      packages: write
    runs-on: ${{ vars.UBUNTU_VERSION }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./alpine-linux.dockerfile
          push: true
          tags: ghcr.io/atomic-works/alpine-linux:latest, ghcr.io/atomic-works/alpine-linux:${{ needs.Create-Release.outputs.tag }}
```

### Acceptance Criteria

- Copy the aforementioned work into `reusable-workflows/deploy-docker-image`.

### Label

- [X] I have assigned a proper work label to this issue.

### Project

- [X] I have assigned this issue to a project.
